language: c
sudo: false
compiler:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  - echo "Travis CI producing a build of streamgeo."

script:
  - cd cstreamgeo && mkdir -p build && cd build && cmake .. && make -j && make test
