language: c
sudo: true
compiler:
  - clang

branches:
  only:
    - master

before_install:
  - git clone https://github.com/RoaringBitmap/CRoaring.git && cd CRoaring && mkdir -p build && cd build && cmake .. && make -j && sudo make install && sudo ldconfig && cd ../..
script:
  - cd cstreamgeo && mkdir -p build && cd build && cmake .. && make -j && make test
